######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 31 23:12:28 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
