######################################################################
# Automatically generated by qmake (3.0) Sat Aug 5 22:50:57 2017
######################################################################

TEMPLATE = app
TARGET = jTest
INCLUDEPATH += .

# Input
HEADERS += simplemenu.h
SOURCES += main.cpp simplemenu.cpp
QT += widgets gui core
