######################################################################
# Automatically generated by qmake (3.0) Wed Aug 2 15:55:33 2017
######################################################################

TEMPLATE = app
TARGET = oldFiles
INCLUDEPATH += .

# Input
SOURCES += pushbutton.cpp
QT +=widgets
