######################################################################
# Automatically generated by qmake (3.0) Wed Aug 2 16:38:45 2017
######################################################################

TEMPLATE = app
TARGET = plusminus
INCLUDEPATH += .

# Input
HEADERS += plusminus.h
SOURCES += main.cpp plusminus.cpp
QT += widgets
