######################################################################
# Automatically generated by qmake (3.0) Sun Aug 13 16:03:05 2017
######################################################################

TEMPLATE = app
TARGET = animation
INCLUDEPATH += .

# Input
SOURCES += animation.cpp
QT += widgets core gui multimedia multimediawidgets
