######################################################################
# Automatically generated by qmake (3.0) Wed Aug 2 23:52:44 2017
######################################################################

TEMPLATE = app
TARGET = video
INCLUDEPATH += .

# Input
SOURCES += videotest.cpp
QT += multimedia widgets multimediawidgets

